[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_mind_protocol = "7GoSe63kVLi3Bt2mkPHUFVbmTcsZvp7QEUHjDB6GvLgV"
nft_operations = "Anv3tR3s1eQqQE1a5wnhtYdi6dkjv9rTn34V6pom9C9q"
dac-manager = "DeXj8mQDYUnLC2mX5xiRqgvYt193sBhJWRZTBkRLg79M"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "bash scripts/build-and-generate.sh"
generate = "bash scripts/generate-clients.sh"
test = "cargo test"
test-verbose = "cargo test -- --show-output"
test-nft-operations = "anchor test --program-name nft_operations"
test-sol-mind-protocol = "anchor test --program-name sol_mind_protocol"

